---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: CSR1kv
  gather_facts: no
  connection: network_cli

  tasks:
    - name: GATHER DEVICE FACTS (GET HOSTNAME)
      ios_facts:
      register: facts_output

    - name: DISPLAY RUNNING-CONFIG
      ios_command:
        commands:
          - show running-config
      register: output

    - name: SAVE OUTPUT TO FILE USING REAL HOSTNAME
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "show_run_66070247_{{ facts_output.ansible_facts.net_hostname }}-Exam.txt"
